# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Terraforming Mars - Ares Expedition

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      FLASK_APP: aresexpedition
      FLASK_ENV: development

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.0'

    - name: Install BE dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Install FE dependencies
      run: npm install
      working-directory: frontend

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test BE
      run: python -m pytest
      working-directory: backend

    - name: Build FE
      run: npm run build
      working-directory: frontend

    - name: Test FE
      run: npm test
      working-directory: frontend
